// VENDORED from components/git-helpers/src/ by scripts/stage-gbfs.mjs.
// Re-run `npm run gbfs:stage -- agent` to re-sync after upstream changes.
// DO NOT EDIT THIS FILE DIRECTLY.

export { resolveSymbolicHead } from './git-helpers.js';
export { detectDefaultBranchViaRemote } from './git-helpers.js';
export { getCurrentBranch } from './git-helpers.js';
export { branchExists } from './git-helpers.js';
export { resolveDefaultBranch } from './default-branch.js';
export { waitForGbfsMount } from './gbfs.js';
export { resolveGbfsBinary } from './gbfs.js';
export { assertSharedRepoBound } from './gbfs.js';
export { resetToStaging, type RunCommandFn } from './reset.js';
