// VENDORED from components/git-helpers/src/ by scripts/stage-gbfs.mjs.
// Re-run `npm run gbfs:stage -- agent` to re-sync after upstream changes.
// DO NOT EDIT THIS FILE DIRECTLY.

import { branchExists } from './git-helpers.js';
import { resolveDefaultBranch } from './default-branch.js';
import {
    assertSharedRepoBound,
    resolveGbfsBinary,
    spawnGbfsMount,
    waitForGbfsMount,
} from './gbfs.js';

export type RunCommandFn = (
    command: string,
    args: string[],
    cwd: string,
) => Promise<{ code: number | null; output: string }>;

export interface ResetOptions {
    sharedRepoPath: string;
    repoPath: string;
    stagingBranch: string;
    runCommand: RunCommandFn;
    /** Override wait-for-mount timeout (ms). Default: 10000. */
    mountTimeoutMs?: number;
}

/**
 * Refresh tracking refs in the shared repo, mount the FUSE view, and
 * align `/repo` with `origin/<stagingBranch>` using the same three-branch
 * "remote is authoritative" rule as web-ui's `doSetupChatMount`:
 *
 *   1. remote + local both present → checkout -B <staging> origin/<staging>
 *   2. only local present          → checkout <staging>
 *   3. neither present             → create <staging> from the default branch + push -u
 *
 * Throws on any failure with a clear message.
 */
export async function resetToStaging(opts: ResetOptions): Promise<void> {
    const { sharedRepoPath, repoPath, stagingBranch, runCommand } = opts;
    const mountTimeoutMs = opts.mountTimeoutMs ?? 10000;

    assertSharedRepoBound(sharedRepoPath);

    const binary = resolveGbfsBinary();
    if (!binary) {
        throw new Error(
            'gbfs binary not found. Expected /gbfs/gbfs (or on PATH, or via GBFS_BINARY env). ' +
            'The container image must install gbfs and libfuse3; see components/agent/Dockerfile.',
        );
    }

    // Refresh tracking refs in the shared repo so origin/<staging> is current.
    const fetch = await runCommand('git', ['fetch', '--prune', 'origin'], sharedRepoPath);
    if (fetch.code !== 0) {
        // Warn-and-continue mirrors web-ui (repo-clone.ts:278-284): a
        // failed fetch (offline / deleted remote) doesn't invalidate
        // the existing local refs.
        const tail = (fetch.output.split('\n').pop() || '').trim() || 'unknown error';
        // eslint-disable-next-line no-console
        console.warn(`git fetch --prune origin failed (continuing): ${tail}`);
    }

    // Mount the FUSE view of staging onto /repo.
    // eslint-disable-next-line no-console
    console.log(`gbfs mount ${stagingBranch} ${repoPath} (cwd=${sharedRepoPath})`);
    const proc = spawnGbfsMount(stagingBranch, repoPath, sharedRepoPath);
    proc.unref();
    proc.on('error', (err) => {
        // eslint-disable-next-line no-console
        console.error(`gbfs mount failed to start: ${err.message}`);
    });

    await waitForGbfsMount(repoPath, mountTimeoutMs);

    const remoteUpstream = await branchExists(repoPath, `origin/${stagingBranch}`);
    const localUpstream = await branchExists(repoPath, stagingBranch);

    if (remoteUpstream && localUpstream) {
        const co = await runCommand('git', ['checkout', '-B', stagingBranch, `origin/${stagingBranch}`], repoPath);
        if (co.code !== 0) {
            throw new Error(`git checkout -B ${stagingBranch} origin/${stagingBranch} failed: ${co.output}`);
        }
    } else if (localUpstream && !remoteUpstream) {
        const co = await runCommand('git', ['checkout', stagingBranch], repoPath);
        if (co.code !== 0) {
            throw new Error(`git checkout ${stagingBranch} failed: ${co.output}`);
        }
    } else {
        const defaultBranch = await resolveDefaultBranch(sharedRepoPath);
        if (defaultBranch) {
            try {
                const co = await runCommand('git', ['checkout', defaultBranch], repoPath);
                if (co.code !== 0) {
                    // eslint-disable-next-line no-console
                    console.warn(`checkout default ${defaultBranch} failed (continuing): ${co.output}`);
                }
            } catch (err: any) {
                // eslint-disable-next-line no-console
                console.warn(`checkout default ${defaultBranch} threw: ${err.message}`);
            }
        }
        const create = await runCommand('git', ['checkout', '-B', stagingBranch], repoPath);
        if (create.code !== 0) {
            throw new Error(`git checkout -B ${stagingBranch} failed: ${create.output}`);
        }
        const push = await runCommand('git', ['push', '-u', 'origin', stagingBranch], repoPath);
        if (push.code !== 0) {
            const tail = (push.output.split('\n').pop() || '').trim() || 'unknown error';
            // eslint-disable-next-line no-console
            console.warn(`push -u origin ${stagingBranch} failed (continuing): ${tail}`);
        }
    }
}
