import { CONFIG } from './config.js';

function parseAdoUrl(repoUrl: string): { org: string; project: string; repoName: string } {
    // URL format: https://dev.azure.com/{org}/{project}/_git/{repo}
    const parts = repoUrl.split('/');
    const org = parts[3] || '';
    const project = parts[4] || '';
    const repoName = parts[parts.length - 1]?.replace('.git', '') || '';
    return { org, project, repoName };
}

async function getAuthenticatedUserId(auth: string, org: string): Promise<string> {
    const connUrl = `https://dev.azure.com/${org}/_apis/connectionData?api-version=7.1-preview`;
    const response = await fetch(connUrl, {
        headers: { 'Authorization': `Basic ${auth}` }
    });
    if (!response.ok) {
        throw new Error(`Failed to get ADO connection data: ${await response.text()}`);
    }
    const data = await response.json();
    return data.authenticatedUser.id;
}

export async function createAndMergePR(sourceBranch: string): Promise<number> {
    if (!CONFIG.REPO_PAT) throw new Error('REPO_TOKEN (repo_pat) not provided for ADO API auth');

    const { org, project, repoName } = parseAdoUrl(CONFIG.REPO_URL);
    if (!org || !project) throw new Error('Invalid ADO repo URL - could not parse org/project');

    const auth = Buffer.from(`:${CONFIG.REPO_PAT}`).toString('base64');
    const baseUrl = `https://dev.azure.com/${org}/${project}/_apis/git/repositories`;

    const prsUrl = `${baseUrl}/${repoName}/pullrequests?api-version=7.1&searchCriteria.sourceRefName=refs/heads/${sourceBranch}&searchCriteria.targetRefName=refs/heads/${CONFIG.STAGING_BRANCH}`;

    console.log(`Checking for existing PR from ${sourceBranch} to ${CONFIG.STAGING_BRANCH}...`);
    const prsResponse = await fetch(prsUrl, {
        headers: { 'Authorization': `Basic ${auth}` }
    });

    let prId: number | undefined;
    let prData: any;

    if (prsResponse.ok) {
        const list = await prsResponse.json();
        if (list.count > 0) {
            prData = list.value[0];
            prId = prData.pullRequestId;
            console.log(`Found existing PR #${prId}. Reusing it.`);
        }
    }

    if (!prId) {
        console.log(`Creating new PR to ${CONFIG.STAGING_BRANCH}...`);
        const prUrl = `${baseUrl}/${repoName}/pullrequests?api-version=7.1`;
        const prBody: Record<string, unknown> = {
            sourceRefName: `refs/heads/${sourceBranch}`,
            targetRefName: `refs/heads/${CONFIG.STAGING_BRANCH}`,
            title: `AI Implementation feature(${CONFIG.JOB_ID}): ${CONFIG.JOB_TITLE}`,
            description: `This PR was automatically generated by an AI Agent.`,
        };

        const response = await fetch(prUrl, {
            method: 'POST',
            headers: {
                'Authorization': `Basic ${auth}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(prBody)
        });

        if (!response.ok) {
            const err = await response.text();
            throw new Error(`Failed to create PR: ${err}`);
        }

        prData = await response.json();
        prId = prData.pullRequestId;
        console.log(`Created new PR #${prId}.`);
    }

    console.log('Waiting 5s for ADO to sync pushed commit...');
    await new Promise(resolve => setTimeout(resolve, 5000));

    const userId = await getAuthenticatedUserId(auth, org);
    const prUrl = `${baseUrl}/${repoName}/pullrequests/${prId}?api-version=7.1`;
    const autoCompleteBody = {
        autoCompleteSetBy: { id: userId },
        completionOptions: {
            deleteSourceBranch: true,
            mergeStrategy: "noFastForward"
        }
    };

    const autoCompleteResponse = await fetch(prUrl, {
        method: 'PATCH',
        headers: {
            'Authorization': `Basic ${auth}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(autoCompleteBody)
    });

    if (!autoCompleteResponse.ok) {
        const err = await autoCompleteResponse.text();
        throw new Error(`Failed to set auto-complete for PR: ${err}`);
    }

    console.log(`Auto-complete set for PR #${prId}. Polling for completion...`);
    let isCompleted = false;
    let attempts = 0;
    const maxAttempts = 30;

    while (!isCompleted && attempts < maxAttempts) {
        await new Promise(resolve => setTimeout(resolve, 10000));
        attempts++;

        const checkResponse = await fetch(prUrl, {
            headers: { 'Authorization': `Basic ${auth}` }
        });

        if (checkResponse.ok) {
            const data = await checkResponse.json();
            if (data.status === 'completed') {
                isCompleted = true;
                console.log(`PR #${prId} merged successfully.`);
            } else if (data.status === 'abandoned') {
                throw new Error(`PR #${prId} was abandoned.`);
            } else {
                console.log(`PR status: ${data.status}, Merge status: ${data.mergeStatus}...`);
                if (data.mergeStatus === 'conflicts') {
                    throw new Error(`PR #${prId} has merge conflicts.`);
                }
                if (data.mergeStatus === 'failure') {
                    throw new Error(`PR #${prId} merge failed.`);
                }
            }
        }
    }

    if (!isCompleted) {
        throw new Error(`PR #${prId} did not complete within timeout.`);
    }

    return prId!;
}
