import { CONFIG } from './config.js';

export async function createAndMergePR(sourceBranch: string): Promise<number> {
    const auth = CONFIG.REPO_PAT;
    if (!auth) throw new Error('REPO_PAT not provided for Bitbucket API auth');

    const repoParts = CONFIG.REPO_URL?.split('/');
    if (!repoParts || repoParts.length < 2) throw new Error('Invalid REPO_URL');
    const repo_slug = repoParts.pop()?.replace('.git', '') ?? '';
    const workspace = repoParts.pop() ?? '';
    if (!workspace || !repo_slug) throw new Error('Invalid REPO_URL');
    const baseUrl = `https://api.bitbucket.org/2.0/repositories/${workspace}/${repo_slug}`;

    console.log(`Checking for existing PR from ${sourceBranch} to ${CONFIG.STAGING_BRANCH}...`);
    const query = `source.branch.name="${sourceBranch}"+AND+destination.branch.name="${CONFIG.STAGING_BRANCH}"+AND+state="OPEN"`;
    const prsUrl = `${baseUrl}/pullrequests?q=${encodeURIComponent(query)}`;
    const prsResponse = await fetch(prsUrl, {
        headers: { 'Authorization': `Bearer ${auth}`, 'Accept': 'application/json' }
    });

    let prId: number | undefined;
    if (prsResponse.ok) {
        const data = await prsResponse.json() as { values?: { id: number }[] };
        if (data.values && data.values.length > 0) {
            const firstPr = data.values[0];
            if (firstPr) {
                prId = firstPr.id;
                console.log(`Found existing PR #${prId}. Reusing it.`);
            }
        }
    }

    if (!prId) {
        console.log(`Creating new PR to ${CONFIG.STAGING_BRANCH}...`);
        const prUrl = `${baseUrl}/pullrequests`;
        const response = await fetch(prUrl, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${auth}`,
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                title: `AI Implementation feature(${CONFIG.JOB_ID}): ${CONFIG.JOB_TITLE}`,
                description: 'This PR was automatically generated by an AI Agent.',
                source: { branch: { name: sourceBranch } },
                destination: { branch: { name: CONFIG.STAGING_BRANCH } }
            })
        });

        if (!response.ok) {
            const err = await response.text();
            throw new Error(`Failed to create PR: ${err}`);
        }

        const prData = await response.json() as { id: number };
        prId = prData.id;
        console.log(`Created new PR #${prId}.`);
    }

    console.log(`Merging PR #${prId}...`);
    const mergeUrl = `${baseUrl}/pullrequests/${prId}/merge`;

    let merged = false;
    let lastMergeErr = '';
    let attempt = 0;

    while (true) {
        attempt++;
        if (attempt > 1) {
            const waitMs = (attempt - 1) * 5000;
            console.log(`Merge attempt ${attempt} — waiting ${waitMs / 1000}s...`);
            await new Promise(r => setTimeout(r, waitMs));
        }

        const mergeResponse = await fetch(mergeUrl, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${auth}`,
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ merge_strategy: 'squash' })
        });

        if (mergeResponse.ok) {
            merged = true;
            break;
        }

        lastMergeErr = await mergeResponse.text();
        const status = mergeResponse.status;

        if (status === 401 || status === 403) {
            throw new Error(`Bitbucket authentication/authorization failed: ${lastMergeErr}`);
        }
        if (status === 404) {
            throw new Error(`PR #${prId} not found: ${lastMergeErr}`);
        }
        if (status === 409) {
            throw new Error(`PR #${prId} has merge conflicts: ${lastMergeErr}`);
        }

        const errLower = lastMergeErr.toLowerCase();
        if (errLower.includes('merge conflict') || errLower.includes('not mergeable')) {
            throw new Error(`PR #${prId} has merge conflicts: ${lastMergeErr}`);
        }

        if (status === 429) {
            console.log(`Merge attempt ${attempt} — rate limited, continuing...`);
            continue;
        }
        if (errLower.includes('not ready') || errLower.includes('try again')) {
            console.log(`Merge attempt ${attempt} — PR not ready yet, continuing...`);
            continue;
        }
        if (errLower.includes('required status checks') || errLower.includes('pending') || errLower.includes('waiting')) {
            console.log(`Merge attempt ${attempt} — CI checks not passed yet, continuing...`);
            continue;
        }

        console.log(`Merge attempt ${attempt} failed (HTTP ${status}): ${lastMergeErr}`);
    }

    console.log(`PR #${prId} merged successfully.`);
    return prId!;
}