import { CONFIG } from './config.js';

export async function createAndMergePR(sourceBranch: string): Promise<number> {
    const auth = CONFIG.REPO_PAT;
    if (!auth) throw new Error('REPO_TOKEN (repo_pat) not provided for GitHub API auth');

    const repoParts = CONFIG.REPO_URL?.split('/');
    if (!repoParts || repoParts.length < 2) throw new Error('Invalid REPO_URL');
    const repoName = repoParts.pop()?.replace('.git', '');
    const owner = repoParts.pop();
    const baseUrl = `https://api.github.com/repos/${owner}/${repoName}`;

    console.log(`Checking for existing PR from ${sourceBranch} to ${CONFIG.STAGING_BRANCH}...`);
    const prsUrl = `${baseUrl}/pulls?head=${owner}:${sourceBranch}&base=${CONFIG.STAGING_BRANCH}&state=open`;
    const prsResponse = await fetch(prsUrl, {
        headers: { 'Authorization': `token ${auth}`, 'Accept': 'application/vnd.github.v3+json' }
    });

    let prNumber: number | undefined;
    if (prsResponse.ok) {
        const list = await prsResponse.json() as any[];
        if (list.length > 0) {
            prNumber = list[0].number;
            console.log(`Found existing PR #${prNumber}. Reusing it.`);
        }
    }

    if (!prNumber) {
        console.log(`Creating new PR to ${CONFIG.STAGING_BRANCH}...`);
        const prUrl = `${baseUrl}/pulls`;
        const title = `AI Implementation feature(${CONFIG.JOB_ID}): ${CONFIG.JOB_TITLE}`;
        const body = `This PR was automatically generated by an AI Agent.`;

        const response = await fetch(prUrl, {
            method: 'POST',
            headers: {
                'Authorization': `token ${auth}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                title,
                body,
                head: sourceBranch,
                base: CONFIG.STAGING_BRANCH
            })
        });

        if (!response.ok) {
            const err = await response.text();
            throw new Error(`Failed to create PR: ${err}`);
        }

        const prData = await response.json() as any;
        prNumber = prData.number;
        console.log(`Created new PR #${prNumber}.`);
    }

    console.log(`Merging PR #${prNumber}...`);
    const mergeUrl = `${baseUrl}/pulls/${prNumber}/merge`;

    let merged = false;
    let lastMergeErr = '';
    let attempt = 0;

    while (true) {
        attempt++;
        if (attempt > 1) {
            const waitMs = (attempt - 1) * 5000;
            console.log(`Merge attempt ${attempt} — waiting ${waitMs / 1000}s...`);
            await new Promise(r => setTimeout(r, waitMs));
        }

        const mergeResponse = await fetch(mergeUrl, {
            method: 'PUT',
            headers: {
                'Authorization': `token ${auth}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                merge_method: 'squash',
                commit_title: `AI Implementation feature(${CONFIG.JOB_ID}): ${CONFIG.JOB_TITLE}`
            })
        });

        if (mergeResponse.ok) {
            merged = true;
            break;
        }

        lastMergeErr = await mergeResponse.text();
        const status = mergeResponse.status;

        if (status === 409) {
            throw new Error(`PR #${prNumber} has merge conflicts: ${lastMergeErr}`);
        }
        if (status === 401 || status === 403) {
            throw new Error(`GitHub authentication/authorization failed: ${lastMergeErr}`);
        }
        if (status === 404) {
            throw new Error(`PR #${prNumber} not found: ${lastMergeErr}`);
        }

        const errLower = lastMergeErr.toLowerCase();

        if (errLower.includes('merge conflict') || errLower.includes('not mergeable')) {
            throw new Error(`PR #${prNumber} has merge conflicts: ${lastMergeErr}`);
        }

        if (errLower.includes('required status checks') || errLower.includes('pending') || errLower.includes('waiting')) {
            console.log(`Merge attempt ${attempt} — CI checks not passed yet, continuing...`);
            continue;
        }

        if (errLower.includes('try again') || errLower.includes('not ready')) {
            console.log(`Merge attempt ${attempt} — PR not ready yet, continuing...`);
            continue;
        }

        if (status === 429) {
            console.log(`Merge attempt ${attempt} — rate limited, continuing...`);
            continue;
        }

        console.log(`Merge attempt ${attempt} failed (HTTP ${status}): ${lastMergeErr}`);
    }

    if (!merged) {
        throw new Error(`Failed to merge PR: ${lastMergeErr}`);
    }

    console.log(`PR #${prNumber} merged successfully.`);
    return prNumber!;
}
