#!/usr/bin/env node
// Copies components/gbfs/gbfs into each requested component directory as
// `gbfs-binary`, which is then `COPY`'d into the Docker image at /gbfs/gbfs
// by the component's Dockerfile. The copy lives in the component dir (rather
// than the build context root) so we don't need to widen the Docker build
// context. It's also gitignored — re-run this script before every docker
// build via the `docker-image-*` npm scripts.
//
// Also vendors components/git-helpers/src into each consumer component as
// `src/git-helpers/` so the consumer's `tsc` step compiles the package
// inline (preserves the consumer's `rootDir: ./src` invariant) and the
// import path stays inside the package (`./git-helpers/index.js`). The
// vendored copies carry a banner comment pointing back at the upstream
// source — re-run stage-gbfs to re-sync after upstream changes.

import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const sourceBinary = resolve(repoRoot, 'components', 'gbfs', 'gbfs');
const gitHelpersSrc = resolve(repoRoot, 'components', 'git-helpers', 'src');

const componentToDir = {
    'web-ui': resolve(repoRoot, 'components', 'web-ui'),
    agent: resolve(repoRoot, 'components', 'agent'),
    tester: resolve(repoRoot, 'components', 'tester'),
};

const gitHelpersConsumers = new Set(['agent', 'tester']);

const requested = process.argv.slice(2);
if (requested.length === 0) {
    console.error('[stage-gbfs] usage: npm run gbfs:stage -- <component> [<component> ...]');
    console.error('[stage-gbfs]   components:', Object.keys(componentToDir).join(', '));
    process.exit(2);
}

if (!existsSync(sourceBinary)) {
    console.error(`[stage-gbfs] source binary not found: ${sourceBinary}`);
    console.error('[stage-gbfs] expected components/gbfs/gbfs to exist on disk.');
    process.exit(1);
}

const banner = (component) => `// VENDORED from components/git-helpers/src/ by scripts/stage-gbfs.mjs.\n` +
    `// Re-run \`npm run gbfs:stage -- ${component}\` to re-sync after upstream changes.\n` +
    `// DO NOT EDIT THIS FILE DIRECTLY.\n\n`;

let staged = 0;
for (const component of requested) {
    const dir = componentToDir[component];
    if (!dir) {
        console.error(`[stage-gbfs] unknown component: ${component}`);
        process.exit(1);
    }
    const target = resolve(dir, 'gbfs-binary');
    copyFileSync(sourceBinary, target);
    console.log(`[stage-gbfs] staged ${target}`);
    staged += 1;

    if (gitHelpersConsumers.has(component)) {
        const vendored = resolve(dir, 'src', 'git-helpers');
        rmSync(vendored, { recursive: true, force: true });
        cpSync(gitHelpersSrc, vendored, { recursive: true });
        for (const file of ['git-helpers.ts', 'default-branch.ts', 'gbfs.ts', 'reset.ts', 'index.ts']) {
            const p = resolve(vendored, file);
            if (!existsSync(p)) continue;
            const current = readFileSync(p, 'utf8');
            if (!current.startsWith('// VENDORED')) {
                writeFileSync(p, banner(component) + current, 'utf8');
            }
        }
        console.log(`[stage-gbfs] vendored ${vendored}`);
        staged += 1;
    }
}

console.log(`[stage-gbfs] staged ${staged} component(s).`);
